spring:
  profiles:
    active:
      - dog
      - EN
      - qa
guru:
  username: YmlUser
  password: YmlPass
  jdbcurl: YmlUrl

# The three dashes effectively a file seperator
---
spring:
  profiles: prod
guru:
  username: YmlProdUser
  password: YmlProdPass
  jdbcurl: YmlProdUrl


---
spring:
  profiles: uat
guru:
  username: YmlUATUser
  password: YmlUATPass
  jdbcurl: YmlUATUrl
